// Expanded product data with enhanced SEO and more products
const products = [
  // ==================== FURNITURE PRODUCTS ====================
  {
    id: 1,
    name: "Ergonomic Study Desk with Drawers",
    category: "Furniture",
    subcategory: "Desks",
    price: 20749,
    originalPrice: 29049,
    rating: 4.8,
    reviews: 456,
    image: "https://via.placeholder.com/300x300?text=Study+Desk",
    description: "Premium adjustable study desk perfect for students and professionals. Features electric height adjustment, cable management, and spacious work surface.",
    longDescription: "Transform your workspace with this premium ergonomic study desk. Designed for comfort and productivity, this desk features adjustable height settings, built-in cable management, 2 spacious drawers for storage, and a durable solid wood frame. Perfect for students, remote workers, and professionals.",
    tags: ["study desk", "adjustable desk", "ergonomic furniture", "student desk", "height adjustable"],
    keywords: "ergonomic study desk, adjustable height desk, student desk with drawers",
    inStock: true,
    featured: true
  },
  {
    id: 2,
    name: "Modern Ergonomic Office Chair Pro",
    category: "Furniture",
    subcategory: "Chairs",
    price: 16599,
    originalPrice: 24899,
    rating: 4.7,
    reviews: 623,
    image: "https://via.placeholder.com/300x300?text=Office+Chair",
    description: "Comfortable and stylish office chair with lumbar support, 360-degree swivel, and adjustable armrests. Perfect for long working hours.",
    longDescription: "Experience ultimate comfort with our ergonomic office chair featuring premium lumbar support, breathable mesh back, adjustable seat height, and padded armrests. Ideal for all-day use in offices, home workspaces, and study areas.",
    tags: ["office chair", "ergonomic chair", "lumbar support", "swivel chair", "comfortable seating"],
    keywords: "ergonomic office chair, lumbar support chair, office furniture",
    inStock: true,
    featured: true
  },
  {
    id: 3,
    name: "Premium Wooden Bookshelf 5-Tier",
    category: "Furniture",
    subcategory: "Storage",
    price: 14949,
    originalPrice: 20749,
    rating: 4.8,
    reviews: 234,
    image: "https://via.placeholder.com/300x300?text=Bookshelf",
    description: "Minimalist wooden bookshelf with 5 shelves. Ideal for storing books and decorative items. Features solid wood construction and modern design.",
    longDescription: "This premium 5-tier wooden bookshelf combines minimalist design with practical storage. Built from solid pine wood, it offers 5 spacious shelves perfect for organizing books, plants, photo frames, and decorative items. Easy assembly and stunning aesthetic.",
    tags: ["bookshelf", "wooden storage", "minimalist decor", "home storage", "book organizer"],
    keywords: "wooden bookshelf, bookcase, home storage furniture",
    inStock: true,
    featured: false
  },
  {
    id: 4,
    name: "Standing Desk Converter Deluxe",
    category: "Furniture",
    subcategory: "Desks",
    price: 12449,
    originalPrice: 16599,
    rating: 4.6,
    reviews: 312,
    image: "https://via.placeholder.com/300x300?text=Desk+Converter",
    description: "Adjustable standing desk converter for better workplace ergonomics. Switch between sitting and standing for better health.",
    longDescription: "Upgrade any workspace with this standing desk converter. Adjustable height, spacious keyboard tray, and monitor riser. Promotes healthy posture and reduces fatigue during long work sessions.",
    tags: ["standing desk", "desk converter", "health workspace", "ergonomic solution", "adjustable height"],
    keywords: "standing desk converter, height adjustable desk riser",
    inStock: true,
    featured: false
  },
  {
    id: 5,
    name: "L-Shaped Corner Gaming Desk",
    category: "Furniture",
    subcategory: "Desks",
    price: 24899,
    originalPrice: 33199,
    rating: 4.9,
    reviews: 187,
    image: "https://via.placeholder.com/300x300?text=Gaming+Desk",
    description: "Spacious L-shaped gaming desk with cable management, monitor stands, and gaming aesthetic. Perfect for gamers and content creators.",
    longDescription: "Designed for gamers and professionals, this L-shaped desk offers ample space for multiple monitors, gaming setup, and work materials. Features built-in cable channels, sturdy frame, and modern gaming aesthetic.",
    tags: ["gaming desk", "L-shaped desk", "corner desk", "gaming furniture", "spacious workspace"],
    keywords: "gaming desk L-shaped, corner gaming desk, large gaming desk",
    inStock: true,
    featured: true
  },
  {
    id: 6,
    name: "Minimalist Coffee Table White",
    category: "Furniture",
    subcategory: "Tables",
    price: 7469,
    originalPrice: 10789,
    rating: 4.5,
    reviews: 156,
    image: "https://via.placeholder.com/300x300?text=Coffee+Table",
    description: "Clean lines minimalist coffee table with hidden storage. Perfect for modern living rooms and compact spaces.",
    longDescription: "Elevate your living room with this minimalist coffee table. Features a clean white finish, hidden storage compartment, and sturdy wooden frame. Perfect for small apartments and modern interiors.",
    tags: ["coffee table", "minimalist furniture", "living room", "hidden storage", "modern design"],
    keywords: "minimalist coffee table, white coffee table, modern living room furniture",
    inStock: true,
    featured: false
  },
  {
    id: 7,
    name: "Industrial Steel Shelving Unit",
    category: "Furniture",
    subcategory: "Storage",
    price: 16599,
    originalPrice: 23239,
    rating: 4.7,
    reviews: 198,
    image: "https://via.placeholder.com/300x300?text=Steel+Shelving",
    description: "Heavy-duty industrial shelving with metal frame and wooden shelves. Durable and perfect for home and office storage.",
    longDescription: "Built to last, this industrial shelving unit features a robust steel frame and premium wooden shelves. Ideal for garages, warehouses, offices, and modern lofts. Supports heavy loads with stylish industrial aesthetic.",
    tags: ["industrial shelving", "metal storage", "garage storage", "heavy-duty", "industrial design"],
    keywords: "industrial shelving unit, metal storage rack, warehouse shelving",
    inStock: true,
    featured: false
  },

  // ==================== HOME DECOR PRODUCTS ====================
  {
    id: 8,
    name: "Modern Wall Art Canvas Set 3-Piece",
    category: "Home Decor",
    subcategory: "Wall Art",
    price: 7469,
    originalPrice: 10789,
    rating: 4.9,
    reviews: 756,
    image: "https://via.placeholder.com/300x300?text=Wall+Art",
    description: "Set of 3 aesthetic wall art canvas paintings. Professional-grade printing with vibrant colors. Perfect for living room or bedroom decoration.",
    longDescription: "Transform your walls with this stunning 3-piece canvas art set. Each canvas features high-quality printing, eco-friendly materials, and comes ready to hang. Perfect for adding personality to any room.",
    tags: ["wall art", "canvas painting", "modern decor", "home decoration", "aesthetic art"],
    keywords: "wall art canvas set, modern wall decor, home decoration art",
    inStock: true,
    featured: true
  },
  {
    id: 9,
    name: "Premium Ceramic Plant Pots Set 5",
    category: "Home Decor",
    subcategory: "Plants & Planters",
    price: 4979,
    originalPrice: 7469,
    rating: 4.8,
    reviews: 512,
    image: "https://via.placeholder.com/300x300?text=Plant+Pots",
    description: "Premium ceramic plant pots in various sizes. Add greenery to your home with style. Includes drainage holes and saucers.",
    longDescription: "Beautiful handcrafted ceramic planters perfect for indoor and outdoor plants. This 5-piece set includes various sizes with drainage holes and decorative saucers. Frost-resistant and weatherproof.",
    tags: ["plant pots", "ceramic planters", "home greenery", "decorative pots", "indoor plants"],
    keywords: "ceramic plant pots, planters set, home plant decor",
    inStock: true,
    featured: false
  },
  {
    id: 10,
    name: "Warm White LED String Lights 50LED",
    category: "Home Decor",
    subcategory: "Lighting",
    price: 2899,
    originalPrice: 4564,
    rating: 4.7,
    reviews: 689,
    image: "https://via.placeholder.com/300x300?text=String+Lights",
    description: "Warm white LED string lights with 50 bulbs. Perfect for creating ambiance in any room. Energy-efficient and long-lasting.",
    longDescription: "Create magical ambiance with these warm white fairy lights. 50 LED bulbs with 16-foot length, waterproof design, and 8-hour timer. Perfect for bedrooms, parties, and outdoor spaces.",
    tags: ["LED string lights", "fairy lights", "decorative lights", "ambient lighting", "energy-efficient"],
    keywords: "LED string lights, fairy lights, warm white lights decor",
    inStock: true,
    featured: false
  },
  {
    id: 11,
    name: "Large Gold-Framed Wall Mirror Circular",
    category: "Home Decor",
    subcategory: "Mirrors",
    price: 6639,
    originalPrice: 9959,
    rating: 4.8,
    reviews: 423,
    image: "https://via.placeholder.com/300x300?text=Mirror",
    description: "Large decorative mirror with golden frame. Enhances room brightness and adds modern aesthetic. Perfect for entryways and living rooms.",
    longDescription: "Make a statement with this stunning circular wall mirror featuring a premium gold frame. The reflective glass amplifies light and opens up spaces. Perfect for modern and contemporary interiors.",
    tags: ["wall mirror", "decorative mirror", "gold frame", "home decoration", "modern furniture"],
    keywords: "decorative wall mirror gold frame, large mirrors for home",
    inStock: true,
    featured: false
  },
  {
    id: 12,
    name: "Macramé Wall Hanging Tapestry",
    category: "Home Decor",
    subcategory: "Wall Art",
    price: 3734,
    originalPrice: 5809,
    rating: 4.6,
    reviews: 298,
    image: "https://via.placeholder.com/300x300?text=Macrame",
    description: "Handmade macramé wall hanging with boho aesthetic. Adds texture and warmth to any room. 100% cotton rope.",
    longDescription: "Beautiful handcrafted macramé tapestry with bohemian style. Made from 100% natural cotton rope. Adds texture and warmth to bedrooms, living rooms, and office spaces.",
    tags: ["macrame tapestry", "boho decor", "wall hanging", "textile art", "handmade"],
    keywords: "macrame wall hanging, boho wall tapestry, handmade wall decor",
    inStock: true,
    featured: true
  },
  {
    id: 13,
    name: "Geometric Abstract Art Print Modern",
    category: "Home Decor",
    subcategory: "Wall Art",
    price: 2489,
    originalPrice: 4149,
    rating: 4.9,
    reviews: 334,
    image: "https://via.placeholder.com/300x300?text=Abstract+Art",
    description: "Modern geometric abstract art print with vibrant colors. Minimalist aesthetic perfect for contemporary homes.",
    longDescription: "Add contemporary flair with this modern geometric art print. High-quality reproduction on premium paper. Perfect for living rooms, bedrooms, and offices.",
    tags: ["abstract art", "geometric print", "modern art", "contemporary decoration", "minimalist"],
    keywords: "abstract art print, geometric wall art, modern home decor",
    inStock: true,
    featured: false
  },
  {
    id: 14,
    name: "Vintage Gold Decorative Frame Set 3",
    category: "Home Decor",
    subcategory: "Frames",
    price: 3319,
    originalPrice: 5809,
    rating: 4.7,
    reviews: 267,
    image: "https://via.placeholder.com/300x300?text=Frames",
    description: "Set of 3 vintage-style gold frames. Perfect for displaying photos, art, or certificates. Comes with hanging hardware.",
    longDescription: "Combine elegance with functionality. This 3-piece frame set features vintage gold finish, includes mounting hardware, and fits 4x6, 5x7, and 8x10 photos.",
    tags: ["picture frames", "gold frames", "photo display", "decorative frames", "vintage style"],
    keywords: "picture frames gold, decorative frames set, photo display frames",
    inStock: true,
    featured: false
  },

  // ==================== STUDY SETUP PRODUCTS ====================
  {
    id: 15,
    name: "Premium LED Desk Lamp with USB Charging",
    category: "Study Setup",
    subcategory: "Lighting",
    price: 4149,
    originalPrice: 6639,
    rating: 4.8,
    reviews: 567,
    image: "https://via.placeholder.com/300x300?text=Desk+Lamp",
    description: "Adjustable LED desk lamp with 3 color temperatures and brightness levels. Built-in USB charging port. Reduces eye strain perfect for long study sessions.",
    longDescription: "Ultimate study companion featuring adjustable brightness (3 levels), 3 color temperatures (warm/neutral/cool), USB charging port, memory function, and touch control. Perfect for students and professionals.",
    tags: ["LED desk lamp", "study light", "office lighting", "eye care", "USB charging lamp"],
    keywords: "LED desk lamp USB charging, eye care desk light, study lamp",
    inStock: true,
    featured: true
  },
  {
    id: 16,
    name: "Complete Desk Organizer Set with 6 Compartments",
    category: "Study Setup",
    subcategory: "Organization",
    price: 3734,
    originalPrice: 5809,
    rating: 4.6,
    reviews: 412,
    image: "https://via.placeholder.com/300x300?text=Organizer",
    description: "Complete desk organizer set with 6 compartments for pens, papers, and supplies. Keep your workspace tidy and productive.",
    longDescription: "Transform your desk with this premium organizer featuring 6 compartments, pen holders, paper trays, and drawer storage. Made from durable bamboo with modern design.",
    tags: ["desk organizer", "office supplies", "workspace organization", "storage solution", "productivity"],
    keywords: "desk organizer set, office organization, desk storage compartments",
    inStock: true,
    featured: false
  },
  {
    id: 17,
    name: "Monitor Stand Riser with Storage Drawer",
    category: "Study Setup",
    subcategory: "Monitor Stands",
    price: 6639,
    originalPrice: 9959,
    rating: 4.7,
    reviews: 289,
    image: "https://via.placeholder.com/300x300?text=Monitor+Stand",
    description: "Elevated monitor stand with storage drawer and keyboard space underneath. Improves posture and workspace efficiency.",
    longDescription: "Professional-grade monitor riser featuring adjustable height, large storage drawer, keyboard tray underneath, and supports up to 50 lbs. Reduces neck strain and improves ergonomics.",
    tags: ["monitor stand", "desk riser", "ergonomic solution", "storage riser", "workspace upgrade"],
    keywords: "monitor stand with storage, desk riser, monitor riser stand",
    inStock: true,
    featured: false
  },
  {
    id: 18,
    name: "Premium Noise Cancelling Headphones Pro",
    category: "Study Setup",
    subcategory: "Audio",
    price: 10789,
    originalPrice: 14949,
    rating: 4.9,
    reviews: 823,
    image: "https://via.placeholder.com/300x300?text=Headphones",
    description: "Premium noise-cancelling headphones with 30-hour battery life. Perfect for distraction-free studying and work. Includes carrying case.",
    longDescription: "Experience pure focus with active noise cancellation technology, 30-hour battery, Bluetooth 5.0, premium sound quality, and comfortable memory foam ear cups. Includes charging case and audio cable.",
    tags: ["noise cancelling headphones", "wireless headphones", "study headphones", "audio equipment", "focus tools"],
    keywords: "noise cancelling headphones, wireless headphones study, audio headphones",
    inStock: true,
    featured: true
  },
  {
    id: 19,
    name: "Ergonomic Keyboard and Mouse Combo Set",
    category: "Study Setup",
    subcategory: "Peripherals",
    price: 4979,
    originalPrice: 7469,
    rating: 4.7,
    reviews: 345,
    image: "https://via.placeholder.com/300x300?text=Keyboard+Mouse",
    description: "Ergonomic keyboard and mouse combo with wireless connectivity. Reduces wrist strain and improves typing comfort for long sessions.",
    longDescription: "Professional-grade wireless keyboard and mouse set featuring ergonomic design, silent keys, precise tracking, 24-month battery life, and USB receiver. Ideal for students and professionals.",
    tags: ["ergonomic keyboard", "wireless keyboard", "office peripherals", "computer accessories", "wrist support"],
    keywords: "ergonomic keyboard mouse combo, wireless keyboard set, ergonomic computer accessories",
    inStock: true,
    featured: false
  },
  {
    id: 20,
    name: "Study Timer Pomodoro Productivity Tool",
    category: "Study Setup",
    subcategory: "Accessories",
    price: 2074,
    originalPrice: 3319,
    rating: 4.8,
    reviews: 267,
    image: "https://via.placeholder.com/300x300?text=Pomodoro+Timer",
    description: "Digital Pomodoro timer for effective study sessions. Features 25/5 minute intervals and alarm notification.",
    longDescription: "Boost productivity with this intuitive Pomodoro timer. LCD display, adjustable intervals, loud alarm, and sleek design. Perfect for time management and focused studying.",
    tags: ["pomodoro timer", "study timer", "productivity tool", "time management", "focus aid"],
    keywords: "pomodoro timer, study timer, productivity timer",
    inStock: true,
    featured: false
  },
  {
    id: 21,
    name: "Blue Light Blocking Glasses Anti-Glare",
    category: "Study Setup",
    subcategory: "Eye Care",
    price: 2899,
    originalPrice: 4979,
    rating: 4.6,
    reviews: 498,
    image: "https://via.placeholder.com/300x300?text=Blue+Light+Glasses",
    description: "Premium blue light blocking glasses with anti-glare coating. Protects eyes during extended screen time. Stylish and comfortable.",
    longDescription: "Protect your eyes with these fashionable blue light glasses. Features anti-glare coating, 99% blue light filtering, UV protection, and comfortable memory frame. Perfect for students and professionals.",
    tags: ["blue light glasses", "anti-glare glasses", "eye protection", "computer glasses", "eye health"],
    keywords: "blue light blocking glasses, computer glasses, anti-glare glasses",
    inStock: true,
    featured: false
  }
];

// Enhanced blog posts data
const blogPosts = [
  {
    id: 1,
    title: "Best Study Table for Students in 2026",
    slug: "best-study-table-for-students",
    excerpt: "Discover the top study tables designed specifically for students to maximize productivity and maintain proper posture.",
    author: "Sarah Johnson",
    date: "April 10, 2026",
    category: "Study Tips",
    image: "https://via.placeholder.com/600x400?text=Study+Table",
    readTime: "5 min read",
    featured: true,
    keywords: "best study table, ergonomic desk for students"
  },
  {
    id: 2,
    title: "Aesthetic Room Setup Ideas for Inspiration",
    slug: "aesthetic-room-setup-ideas",
    excerpt: "Transform your room into an aesthetic haven with these modern and minimalist setup ideas that inspire creativity.",
    author: "David Chen",
    date: "April 8, 2026",
    category: "Room Setup",
    image: "https://via.placeholder.com/600x400?text=Room+Setup",
    readTime: "7 min read",
    featured: true,
    keywords: "aesthetic room setup, minimalist room design, bedroom decoration ideas"
  },
  {
    id: 3,
    title: "Top Home Decor Trends for 2026",
    slug: "top-home-decor-trends",
    excerpt: "Stay updated with the latest home decor trends that are dominating the market this year.",
    author: "Emma Wilson",
    date: "April 5, 2026",
    category: "Home Decor",
    image: "https://via.placeholder.com/600x400?text=Decor+Trends",
    readTime: "6 min read",
    featured: true,
    keywords: "home decor trends 2026, interior design trends, modern room decor"
  },
  {
    id: 4,
    title: "How to Organize Your Study Space for Maximum Productivity",
    slug: "organize-study-space",
    excerpt: "Learn effective organization techniques to create a productive study environment that enhances focus and learning.",
    author: "Sarah Johnson",
    date: "April 3, 2026",
    category: "Study Tips",
    image: "https://via.placeholder.com/600x400?text=Organized+Space",
    readTime: "5 min read",
    featured: false,
    keywords: "study space organization, productive workspace setup, focus environment"
  },
  {
    id: 5,
    title: "Ultimate Guide to Home Office Setup in 2026",
    slug: "home-office-setup-guide",
    excerpt: "Create the perfect home office with our comprehensive guide to furniture, lighting, and ergonomic solutions.",
    author: "John Smith",
    date: "April 1, 2026",
    category: "Work From Home",
    image: "https://via.placeholder.com/600x400?text=Home+Office",
    readTime: "8 min read",
    featured: true,
    keywords: "home office setup, work from home furniture, remote work desk"
  },
  {
    id: 6,
    title: "Minimalist Interior Design: Less is More",
    slug: "minimalist-interior-design",
    excerpt: "Embrace minimalism with our guide to creating clean, stylish spaces with intentional design choices.",
    author: "Lisa Anderson",
    date: "March 28, 2026",
    category: "Design Tips",
    image: "https://via.placeholder.com/600x400?text=Minimalist+Design",
    readTime: "6 min read",
    featured: false,
    keywords: "minimalist design, minimalist home decor, minimalist interior"
  }
];
